# Generated by Django 5.2.11 on 2026-02-13 11:38

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_text_alter_document_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding_id',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
