# Generated by Django 5.2.11 on 2026-02-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_documentchunk_embedding_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='embedding',
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
